{% set name = 'psqlODBC' %}
{% set version = '16.00.0005' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/postgresql-interfaces/psqlodbc/archive/refs/tags/REL-{{ version|replace('.','_') }}.tar.gz
  sha256: 1aa1bd5f9cb26ac1a4729ed2ab48974b29c335bebff6830d66aaac8bcd081ab0

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python >=3.6
    - make
    - autoconf
    - automake
  host:
    - unixodbc
    - postgresql
  run:
    - unixodbc
    - libpq

test:
  commands:
    - conda inspect linkages psqlodbc
    # This is using .so on both osx and linux
    - test -f $PREFIX/lib/psqlodbca.so  # [unix]
    - test -f $PREFIX/lib/psqlodbcw.so  # [unix]

about:
  home: https://odbc.postgresql.org/
  license: LGPL-2.0
  license_family: GPL
  license_file: license.txt
  summary: psqlODBC is the official PostgreSQL ODBC Driver
  doc_url: https://odbc.postgresql.org/
  dev_url: https://git.postgresql.org/gitweb/?p=psqlodbc.git

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
