{% set name = "psqlODBC" %}
{% set version = "17_00_0007" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/postgresql-interfaces/psqlodbc/archive/refs/tags/REL-{{ version|replace('.','_') }}.tar.gz
  sha256: cf15619e7fcc31ce3f61634243ca9fbb1e1c7dfdac19d7bda2a66483c029d4b5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - python >=3.6
    - make
    - autoconf
    - automake
    - libtool
  host:
    - unixodbc
    - postgresql
  run:
    - unixodbc
    - libpq

test:
  commands:
    # This is using .so on both osx and linux
    - test -f $PREFIX/lib/psqlodbca.so  # [unix]
    - test -f $PREFIX/lib/psqlodbcw.so  # [unix]

about:
  home: https://odbc.postgresql.org/
  license: LGPL-2.0-or-later
  license_family: GPL
  license_file: license.txt
  summary: psqlODBC is the official PostgreSQL ODBC Driver
  doc_url: https://odbc.postgresql.org/
  dev_url: https://git.postgresql.org/gitweb/?p=psqlodbc.git

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
